[package]
name = "training"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "training"
path = "src/main.rs"

[dependencies]
candle-core = { workspace = true }
candle-nn = { workspace = true }
anyhow = { workspace = true }
shared = { path = "../shared" }
rand = "0.8"

[dev-dependencies]
tempfile = "3.0"